Contraction={
    "aren't": "are not",
    "can't": "cannot",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "isn't": "is not",
    "mightn't": "might not",
    "mustn't": "must not",
    "shan't": "shall not",
    "shouldn't": "should not",
    "wasn't": "was not",
    "weren't": "were not",
    "won't": "will not",
    "wouldn't": "would not",
    "I'm": "I am",
    "you're": "you are",
    "we're": "we are",
    "they're": "they are",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "that's": "that is",
    "there's": "there is",
    "who's": "who is",
    "what's": "what is",
    "where's": "where is",
    "here's": "here is",
    "how's": "how is",
    "let's": "let us",
    "I'll": "I will",
    "you'll": "you will",
    "he'll": "he will",
    "she'll": "she will",
    "it'll": "it will",
    "we'll": "we will",
    "they'll": "they will",
    "I'll've": "I will have",
    "you'll've": "you will have",
    "he'll've": "he will have",
    "she'll've": "she will have",
    "it'll've": "it will have",
    "we'll've": "we will have",
    "they'll've": "they will have",
    "I'd": "I would",
    "you'd": "you would",
    "he'd": "he would",
    "she'd": "she would",
    "we'd": "we would",
    "they'd": "they would",
    "I've": "I have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "he's": "he has",
    "she's": "she has",
    "who's": "who has",
    "what's": "what has",
    "where's": "where has",
    "there's": "there has",
    "how's": "how has",
    "I'd've": "I would have",
    "you'd've": "you would have",
    "he'd've": "he would have",
    "she'd've": "she would have",
    "we'd've": "we would have",
    "they'd've": "they would have",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "ain't": "is not / are not / am not",
    "lemme": "let me",
    "gimme": "give me",
    "kinda": "kind of",
    "sorta": "sort of",
    "coulda": "could have",
    "woulda": "would have",
    "shoulda": "should have",
    "y'all": "you all"
}